In [1]:
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
import pandas as pd

matplotlib.rcParams["font.family"] = "Linux Libertine O"
matplotlib.rcParams["pdf.fonttype"] = 42
matplotlib.rcParams["ps.fonttype"] = 42
dirbase = "figures/eval/"
ourSys = "EinNet"

sz, fontsz = (6, 3), 16
figsz = {
    "axes.labelsize": 14,
    "font.size": 14,
    "legend.fontsize": 14,
    "xtick.labelsize": 12,
    "ytick.labelsize": 12,
    "figure.figsize": (6, 3),
    "axes.titlesize": 14,
}
plt.rcParams.update(figsz)

hb = "\\\\//\\\\//"

color_def = [
    "#f4b183",
    "#ffd966",
    "#c5e0b4",
    "#bdd7ee",
    "#8dd3c7",
    "#bebada",
    "#fb8072",
    "#80b1d3",
    "#fdb462",
    "#cccccc",
    "#fccde5",
    "#b3de69",
    "#ffd92f",
    "#fc8d59",
    "#74a9cf",
    "#66c2a4",
    "#f4a143",
    "#ffc936",
    "#78c679",
]

color_line = [
    "#5AA469",
    "#1A508B",
    "#F39233",
    "#B61919",
]

hatch_def = [
    "//",
    "\\\\",
    "xx",
    "++",
    "--",
    "||",
    "..",
    "oo",
    "",
]

marker_def = [
    "o",
    "x",
    "D",
    "*",
    "+",
]

In [2]:
data_set = pd.read_parquet(
    "/home/zly/Works/uniserving/exp/dataset/pickapci/train-00000-of-00001-b138676ed2d1f52a.parquet", 
    engine="fastparquet" # Unique ratio: num_unique/num_all=0.1
    # "/home/zly/Works/uniserving/exp/dataset/data_diffusiondb/metadata.parquet", engine="fastparquet" # Unique ratio: num_unique/num_all=0.764257
)
data_set

,are_different,best_image_uid,caption,created_at,has_label,image_0_uid,image_0_url,image_1_uid,image_1_url,label_0,label_1,model_0,model_1,ranking_id,user_id,num_example_per_prompt,__index_level_0__
0,True,63b9f453-d3d6-4d6e-bca2-f6752fc8dd63,A panda bear as a mad scientist,2023-03-22 14:11:18.787846,True,63b9f453-d3d6-4d6e-bca2-f6752fc8dd63,https://text-to-image-human-preferences.s3.us-...,bd5f4d7a-2a6c-4437-bacb-c1fa2173e256,https://text-to-image-human-preferences.s3.us-...,1.0,0.0,SDXL-BETA,SDXL-ALPHA,404122,4527,1593,0
1,True,1ed66517-3b84-4104-9e84-56b267b9792d,"photo of a bicycle, detailed, 8k uhd, dslr, hi...",2023-03-19 20:44:51.985629,True,39103e97-1126-43c3-b5e9-6fd3600bac40,https://text-to-image-human-preferences.s3.us-...,1ed66517-3b84-4104-9e84-56b267b9792d,https://text-to-image-human-preferences.s3.us-...,0.0,1.0,DP2.0,SDXL-BETA,233157,1698,33,1
2,False,97f21dbb-43ec-4e78-b789-5b3e8bb0a8de,female portrait photo,2023-03-06 14:34:51.781292,True,97f21dbb-43ec-4e78-b789-5b3e8bb0a8de,https://text-to-image-human-preferences.s3.us-...,52cf107b-aa09-4250-9322-d7093f778d9f,https://text-to-image-human-preferences.s3.us-...,1.0,0.0,SD2.1,SD2.1,70788,1698,99,2
3,True,f6b61748-60b3-40f0-abac-1f55671cc1ce,A man with branches for arms and leaves for ha...,2023-03-28 17:55:45.728095,True,f6b61748-60b3-40f0-abac-1f55671cc1ce,https://text-to-image-human-preferences.s3.us-...,8d814f24-4355-4247-aa35-931859e0a233,https://text-to-image-human-preferences.s3.us-...,1.0,0.0,SDXL-ALPHA,SDXL-BETA,671285,6394,10,4
4,True,none,"Masterpiece, best quality, sand demons battle ...",2023-03-20 13:21:34.778806,False,6e4be13d-e2cc-4bc0-b562-0e0166d8149c,https://text-to-image-human-preferences.s3.us-...,58498767-0484-4fd1-b26c-abfd8a0aff1e,https://text-to-image-human-preferences.s3.us-...,0.5,0.5,DP2.0,SDXL-ALPHA,245967,2508,17,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
583742,False,38659b06-8318-4973-9cf6-a1f5f0263208,a close up of a frog wearing a military unifor...,2023-03-15 15:04:30.313551,True,38659b06-8318-4973-9cf6-a1f5f0263208,https://text-to-image-human-preferences.s3.us-...,cbfdbfa5-7531-4fb9-b03a-1d576590293e,https://text-to-image-human-preferences.s3.us-...,1.0,0.0,DP2.0,DP2.0,197425,3131,15,615254
583743,True,5350bddd-6282-485c-875b-4ecdd83feac8,Stars in a silhouette of a dog,2023-03-22 18:23:11.218791,True,5350bddd-6282-485c-875b-4ecdd83feac8,https://text-to-image-human-preferences.s3.us-...,7a6dbcbd-b332-4939-9e68-dbaf68b761ee,https://text-to-image-human-preferences.s3.us-...,1.0,0.0,DP2.0,SDXL-BETA,425203,1680,9,615255
583744,True,93ee211f-4ccc-4683-93f7-b6c20e891a48,Portrait of a young woman by Roberto ferri and...,2023-03-25 04:35:34.920298,True,5f65de55-248f-4869-843c-cf2809e1ae1b,https://text-to-image-human-preferences.s3.us-...,93ee211f-4ccc-4683-93f7-b6c20e891a48,https://text-to-image-human-preferences.s3.us-...,0.0,1.0,SDXL-BETA,DP2.0,564682,4111,23,615256
583745,True,82271097-3982-414b-a8af-55d9fcaecc90,giant orange glowing humanoid with a sign sayi...,2023-03-19 19:03:38.262063,True,82271097-3982-414b-a8af-55d9fcaecc90,https://text-to-image-human-preferences.s3.us-...,ac135b41-1359-41a3-83e6-c0f0768cb80e,https://text-to-image-human-preferences.s3.us-...,1.0,0.0,SDXL-BETA,DP2.0,227691,3381,14,615257
583746,False,46d063b7-453d-4f3f-b730-88b960b53117,"Well cum back, young girl",2023-03-17 23:49:11.983737,True,beb283a6-df17-4aad-a4d7-d8cdc0d29849,https://text-to-image-human-preferences.s3.us-...,46d063b7-453d-4f3f-b730-88b960b53117,https://text-to-image-human-preferences.s3.us-...,0.0,1.0,DP2.0,DP2.0,212506,2323,4,615258

In [3]:
data_set.sort_values(by=["created_at"], inplace=True)
data_set

,are_different,best_image_uid,caption,created_at,has_label,image_0_uid,image_0_url,image_1_uid,image_1_url,label_0,label_1,model_0,model_1,ranking_id,user_id,num_example_per_prompt,__index_level_0__
322091,False,757d14e3-eadd-40d5-a829-d7e324eaddbb,"8k resolution, realistic digital painting of a...",2023-02-18 02:45:21.940207,True,757d14e3-eadd-40d5-a829-d7e324eaddbb,https://text-to-image-human-preferences.s3.us-...,9425d7eb-21a7-4653-b7f4-3c0be45837a1,https://text-to-image-human-preferences.s3.us-...,1.0,0.0,SD2.1,SD2.1,39666,1374,6,339667
531369,True,cd16741e-d450-4e01-bb42-52568a9f501b,"8k resolution, realistic digital painting of a...",2023-02-18 02:45:29.036119,True,757d14e3-eadd-40d5-a829-d7e324eaddbb,https://text-to-image-human-preferences.s3.us-...,cd16741e-d450-4e01-bb42-52568a9f501b,https://text-to-image-human-preferences.s3.us-...,0.0,1.0,SD2.1,DP2.0,39667,1374,6,560047
482648,False,b10ff478-fa7a-4deb-8a91-602329b6409a,"8k resolution, realistic digital painting of a...",2023-02-18 02:45:33.492213,True,b10ff478-fa7a-4deb-8a91-602329b6409a,https://text-to-image-human-preferences.s3.us-...,cd16741e-d450-4e01-bb42-52568a9f501b,https://text-to-image-human-preferences.s3.us-...,1.0,0.0,DP2.0,DP2.0,39668,1374,6,508679
310123,False,b10ff478-fa7a-4deb-8a91-602329b6409a,"8k resolution, realistic digital painting of a...",2023-02-18 02:45:52.738523,True,b10ff478-fa7a-4deb-8a91-602329b6409a,https://text-to-image-human-preferences.s3.us-...,a98abcf7-d72f-4a1f-8923-a475d4dbeadc,https://text-to-image-human-preferences.s3.us-...,1.0,0.0,DP2.0,DP2.0,39669,1374,6,327066
120034,False,b10ff478-fa7a-4deb-8a91-602329b6409a,"8k resolution, realistic digital painting of a...",2023-02-18 02:46:00.426171,True,b10ff478-fa7a-4deb-8a91-602329b6409a,https://text-to-image-human-preferences.s3.us-...,9f191e9b-d95c-4680-b8c8-5d2d536a199c,https://text-to-image-human-preferences.s3.us-...,1.0,0.0,DP2.0,DP2.0,39670,1374,6,126997
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
399885,False,134ab6de-041f-45cf-b1fb-5307bd694104,"Detailed zombie dolphins, Scary Deep Ocean, pe...",2023-04-12 18:11:21.224000,True,c0f55cf2-7ed6-4d30-966d-2adbd4f01f66,https://text-to-image-human-preferences.s3.us-...,134ab6de-041f-45cf-b1fb-5307bd694104,https://text-to-image-human-preferences.s3.us-...,0.0,1.0,SDXL-BETA,SDXL-BETA,859637,3804,8,421565
461724,True,134ab6de-041f-45cf-b1fb-5307bd694104,"Detailed zombie dolphins, Scary Deep Ocean, pe...",2023-04-12 18:11:21.874747,True,9c6c37a2-6bf7-42b4-9b22-32803621dd76,https://text-to-image-human-preferences.s3.us-...,134ab6de-041f-45cf-b1fb-5307bd694104,https://text-to-image-human-preferences.s3.us-...,0.0,1.0,SDXL-BETA-3,SDXL-BETA,859638,3804,8,486671
275495,True,134ab6de-041f-45cf-b1fb-5307bd694104,"Detailed zombie dolphins, Scary Deep Ocean, pe...",2023-04-12 18:15:36.292049,True,134ab6de-041f-45cf-b1fb-5307bd694104,https://text-to-image-human-preferences.s3.us-...,d6e1536d-8b50-485c-a434-61d3a6a5ac93,https://text-to-image-human-preferences.s3.us-...,1.0,0.0,SDXL-BETA,SDXL-BETA-3,859639,3804,8,290582
303752,False,134ab6de-041f-45cf-b1fb-5307bd694104,"Detailed zombie dolphins, Scary Deep Ocean, pe...",2023-04-12 18:15:38.122824,True,134ab6de-041f-45cf-b1fb-5307bd694104,https://text-to-image-human-preferences.s3.us-...,016aae52-aa77-4bbf-aeb0-80cedfbb4639,https://text-to-image-human-preferences.s3.us-...,1.0,0.0,SDXL-BETA,SDXL-BETA,859640,3804,8,320357
332676,False,134ab6de-041f-45cf-b1fb-5307bd694104,"Detailed zombie dolphins, Scary Deep Ocean, pe...",2023-04-12 18:15:38.752998,True,134ab6de-041f-45cf-b1fb-5307bd694104,https://text-to-image-human-preferences.s3.us-...,32e0fe97-6356-49c5-b0e5-e2380df6d89a,https://text-to-image-human-preferences.s3.us-...,1.0,0.0,SDXL-BETA,SDXL-BETA,859641,3804,8,350825

In [12]:
data_set.iloc[0]['image_1_url']

'https://text-to-image-human-preferences.s3.us-east-2.amazonaws.com/images/9425d7eb-21a7-4653-b7f4-3c0be45837a1.png'

In [4]:
def calc_ratio(data_set):
    prompt_all=data_set['caption']
    prompt_unique=prompt_all.unique()
    num_all=len(prompt_all)
    num_unique=len(prompt_unique)
    print(f'{num_all=} {num_unique=} {num_unique/num_all=}')
    return prompt_all
prompt_all = calc_ratio(data_set)

num_all=583747 num_unique=37523 num_unique/num_all=0.06427955946668677

In [5]:
counts = prompt_all.value_counts()
del data_set

In [6]:
cnt_occurrence=counts.groupby(counts).count()
cnt_occurrence

count
1       5127
2       1201
3       2376
4       2164
5       3724
        ...
1593       1
1670       1
1684       1
1788       1
2584       1
Name: count, Length: 313, dtype: int64

In [7]:
group_occurrence = cnt_occurrence.groupby(pd.cut(cnt_occurrence.index, [0, 1, 5, 10, 10000])).sum()
group_occurrence

/tmp/ipykernel_2671603/352291794.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  group_occurrence = cnt_occurrence.groupby(pd.cut(cnt_occurrence.index, [0, 1, 5, 10, 10000])).sum()

(0, 1]          5127
(1, 5]          9465
(5, 10]         7432
(10, 10000]    15499
Name: count, dtype: int64

In [8]:
cnt_queries = cnt_occurrence.index.astype('int') * cnt_occurrence.values
cnt_queries = cnt_queries.to_series(index = cnt_occurrence.index)
# cnt_occurrence.values

group_occurrence = cnt_queries.groupby(pd.cut(cnt_queries.index, [0, 1, 5, 10, 10000])).sum()
group_occurrence

/tmp/ipykernel_2671603/827840140.py:5: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  group_occurrence = cnt_queries.groupby(pd.cut(cnt_queries.index, [0, 1, 5, 10, 10000])).sum()

(0, 1]           5127
(1, 5]          36806
(5, 10]         57165
(10, 10000]    484649
Name: count, dtype: int64

In [ ]:
def draw_pie_chart(keys, values):
    # TODO: plot the figure with correct labels
    fig, ax = plt.subplots()

    ax.pie(values, labels=keys, autopct='%1.1f%%', colors=color_def, textprops={'fontsize': 16})

    # series.plot(kind='pie', autopct='%1.1f%%', label)
    plt.axis('equal')  # Equal aspect ratio ensures that pie is drawn as a circle.
    plt.savefig("figures/pie.pdf", bbox_inches='tight')
    plt.show()

draw_pie_chart(['1', '2-5', '6-10', '>10'], group_occurrence.values)

In [7]:
prompt_all.str.len().describe()

count    1.400000e+07
mean     1.703520e+02
std      1.145286e+02
min      0.000000e+00
25%      7.600000e+01
50%      1.520000e+02
75%      2.490000e+02
max      1.923000e+03
Name: prompt, dtype: float64

In [8]:
prompt_tokens = prompt_all.apply(lambda x: len(x.split()))
prompt_tokens.describe()

count    1.400000e+07
mean     2.570424e+01
std      1.664061e+01
min      0.000000e+00
25%      1.200000e+01
50%      2.300000e+01
75%      3.700000e+01
max      4.800000e+02
Name: prompt, dtype: float64

In [11]:
prompt_unique_tokens = pd.Series(prompt_unique).apply(lambda x: len(x.split()))
prompt_unique_tokens.describe()

count    1.819808e+06
mean     2.314020e+01
std      1.589169e+01
min      0.000000e+00
25%      1.000000e+01
50%      2.000000e+01
75%      3.400000e+01
max      4.800000e+02
dtype: float64